[package]
name = "naga_oil"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# serialize/deserialize required for prune only, todo feature
naga = { version = "0.9", features=["serialize", "deserialize", "wgsl-in", "wgsl-out", "glsl-in", "glsl-out"] }
tracing = "*"
regex = "1.5"
thiserror = "1.0"
codemap = "0.1.3"
codemap-diagnostic = "0.1.1"
codespan-reporting = "0.11.1"

# required for prune only, todo feature
serde = "*"      
serde_json = "*"

[dev-dependencies]
# uncomment for pbr_prune_test example
# bevy = { git = "https://github.com/robtfm/expose_processed_shaders"}
wgpu = { version = "0.13", features=["naga"] }
futures-lite = "*"