[package]
name = "naga_oil"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# serialize/deserialize required for prune only, todo feature
naga = { version = "0.9", features=["serialize", "deserialize", "wgsl-in", "wgsl-out"] }
tracing = "*"
regex = "1.5"

# required for prune only, todo feature
serde = "*"      
serde_json = "*"

[dev-dependencies]
bevy = "0.8"
wgpu = "*"
futures-lite = "*"